### ISSUE TITLE
大佬能否增加一个可以批量下载非同一域下的分享链接里的文件

### ISSUE THREAD

**Issue by MisakaNo23300** [milin2436/oneshow#1]

**Comment by milin2436** [comment]
看了一下onedirve的分享功能，并没有官方的api去获取下载链接，得自己解析html去抓取下载链接，并且解决认证问题，还得应对以后onedrive如果后续html页面有改变，代码也得相应的调整。这与我基于官方api做开发有些矛盾，所以不打算将该功能加入该项目。
为了解决你的需求，粗糙的基于wget命令写了一个shell脚本，来解决批量下载问题。
https://github.com/milin2436/oneshow/blob/main/tools/odshare.sh
该脚本得配合浏览器使用，而且只能处理没有密码的情况，且仅能下载一个目录下所有的文件，不递归子目录。
不支持个人版onedrive。
使用方法:
先执行登录，去获取session信息
./odshare.sh login 分享的链接
然后，用浏览器，选择要下载的目录的URL，执行下面代码下载
./odshare.sh dl 浏览器里目录的URL拷贝
注意：如果下载的目录有子目录，会产生垃圾文件，自行删除即可。

如果想下载有密码的分享，忽略第一步，可直接将浏览器的session按照wget要求的格式拷贝到od-se.txt文件.

**Comment by MisakaNo23300** [comment]
**万分感谢大佬！！！**
